@startuml

title __STRATEGY_PATTERN_EXAMPLE's Class Diagram__\n

  namespace pattern_examples.strategy_pattern_example {
    class pattern_examples.strategy_pattern_example.BubbleSort {
        + sort()
    }
  }
  

  namespace pattern_examples.strategy_pattern_example {
    class pattern_examples.strategy_pattern_example.InsertionSort {
        + sort()
    }
  }
  

  namespace pattern_examples.strategy_pattern_example {
    class pattern_examples.strategy_pattern_example.Main {
        {static} + main()
    }
  }
  

  namespace pattern_examples.strategy_pattern_example {
    class pattern_examples.strategy_pattern_example.SelectionSort {
        + sort()
    }
  }
  

  namespace pattern_examples.strategy_pattern_example {
    interface pattern_examples.strategy_pattern_example.Sorting {
        {abstract} + sort()
    }
  }
  

  namespace pattern_examples.strategy_pattern_example {
    class pattern_examples.strategy_pattern_example.StrategyClient {
        + setStrategy()
        ~ executeStrategy()
    }
  }
  

  pattern_examples.strategy_pattern_example.BubbleSort .up.|> pattern_examples.strategy_pattern_example.Sorting
  pattern_examples.strategy_pattern_example.InsertionSort .up.|> pattern_examples.strategy_pattern_example.Sorting
  pattern_examples.strategy_pattern_example.SelectionSort .up.|> pattern_examples.strategy_pattern_example.Sorting
  pattern_examples.strategy_pattern_example.StrategyClient o-- pattern_examples.strategy_pattern_example.Sorting : strategy


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
