@startuml

title __OBSERVER_PATTERN_EXAMPLE's Class Diagram__\n

  namespace pattern_examples.observer_pattern_example {
    class pattern_examples.observer_pattern_example.ConsoleObserver {
        + handleEvent()
    }
  }
  

  namespace pattern_examples.observer_pattern_example {
    class pattern_examples.observer_pattern_example.FileObserver {
        + handleEvent()
    }
  }
  

  namespace pattern_examples.observer_pattern_example {
    class pattern_examples.observer_pattern_example.Main {
        {static} + main()
    }
  }
  

  namespace pattern_examples.observer_pattern_example {
    class pattern_examples.observer_pattern_example.MeteoStation {
        ~ observers : List<Observer>
        ~ pressure : int
        ~ temperature : int
        + addObserver()
        + notifyObserver()
        + removeObserver()
        + setMeasurements()
    }
  }
  

  namespace pattern_examples.observer_pattern_example {
    interface pattern_examples.observer_pattern_example.Observed {
        {abstract} + addObserver()
        {abstract} + notifyObserver()
        {abstract} + removeObserver()
    }
  }
  

  namespace pattern_examples.observer_pattern_example {
    interface pattern_examples.observer_pattern_example.Observer {
        {abstract} + handleEvent()
    }
  }
  

  pattern_examples.observer_pattern_example.ConsoleObserver .up.|> pattern_examples.observer_pattern_example.Observer
  pattern_examples.observer_pattern_example.FileObserver .up.|> pattern_examples.observer_pattern_example.Observer
  pattern_examples.observer_pattern_example.MeteoStation .up.|> pattern_examples.observer_pattern_example.Observed


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
