@startuml

title __TASK_5's Class Diagram__\n

  namespace tasks.task_5 {
    class tasks.task_5.Book {
        - name : String
        + Book()
        + toString()
    }
  }
  

  namespace tasks.task_5 {
    class tasks.task_5.Magazine {
        - name : String
        + Magazine()
        + getName()
        + toString()
    }
  }
  

  namespace tasks.task_5 {
    class tasks.task_5.Main {
        {static} + main()
    }
  }
  

  namespace tasks.task_5 {
    interface tasks.task_5.Observed {
        {abstract} + addObserver()
        {abstract} + notifyObserver()
    }
  }
  

  namespace tasks.task_5 {
    interface tasks.task_5.Observer {
        {abstract} + handleEvent()
    }
  }
  

  namespace tasks.task_5 {
    class tasks.task_5.PostalOffice {
        ~ observers : List<Observer>
        - books : List<Book>
        - magazines : List<Magazine>
        + addObserver()
        + handleEvent()
        + notifyObserver()
    }
  }
  

  namespace tasks.task_5 {
    class tasks.task_5.Publisher {
        - books : List<Book>
        - magazines : List<Magazine>
        - postalOffices : List<Observer>
        + Publisher()
        + addObserver()
        + notifyObserver()
    }
  }
  

  namespace tasks.task_5 {
    class tasks.task_5.Subscriber1 {
        + handleEvent()
    }
  }
  

  namespace tasks.task_5 {
    class tasks.task_5.Subscriber2 {
        + handleEvent()
    }
  }
  

  namespace tasks.task_5 {
    class tasks.task_5.Subscriber3 {
        + handleEvent()
    }
  }
  

  tasks.task_5.PostalOffice .up.|> tasks.task_5.Observed
  tasks.task_5.PostalOffice .up.|> tasks.task_5.Observer
  tasks.task_5.Publisher .up.|> tasks.task_5.Observed
  tasks.task_5.Subscriber1 .up.|> tasks.task_5.Observer
  tasks.task_5.Subscriber2 .up.|> tasks.task_5.Observer
  tasks.task_5.Subscriber3 .up.|> tasks.task_5.Observer


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
