@startuml

title __TASK_7's Class Diagram__\n

  namespace tasks.task_7 {
    class tasks.task_7.ConfirmedOrder {
        - name : String
        + ConfirmedOrder()
        + getName()
        + getStateOfOrder()
    }
  }
  

  namespace tasks.task_7 {
    class tasks.task_7.ConsideredOrder {
        - name : String
        + ConsideredOrder()
        + getName()
        + getStateOfOrder()
    }
  }
  

  namespace tasks.task_7 {
    class tasks.task_7.CreatedOrder {
        - name : String
        + CreatedOrder()
        + getName()
        + getStateOfOrder()
    }
  }
  

  namespace tasks.task_7 {
    class tasks.task_7.Main {
        {static} + main()
    }
  }
  

  namespace tasks.task_7 {
    class tasks.task_7.MyOrder {
        - name : String
        + MyOrder()
        + getName()
        + getStateOfOrder()
    }
  }
  

  namespace tasks.task_7 {
    class tasks.task_7.OrderGrant {
        - countOfStepsConsideration : int
        + getCountOfStepsConsideration()
        + setState()
        ~ getStateOfOrder()
        ~ nextState()
    }
  }
  

  namespace tasks.task_7 {
    class tasks.task_7.PostponedOrder {
        - name : String
        + PostponedOrder()
        + getName()
        + getStateOfOrder()
    }
  }
  

  namespace tasks.task_7 {
    class tasks.task_7.RejectedOrder {
        - name : String
        + RejectedOrder()
        + getName()
        + getStateOfOrder()
    }
  }
  

  namespace tasks.task_7 {
    interface tasks.task_7.State {
        {abstract} + getName()
        {abstract} + getStateOfOrder()
    }
  }
  

  namespace tasks.task_7 {
    class tasks.task_7.WithdrawnOrder {
        - name : String
        + WithdrawnOrder()
        + getName()
        + getStateOfOrder()
    }
  }
  

  tasks.task_7.ConfirmedOrder .up.|> tasks.task_7.State
  tasks.task_7.ConsideredOrder .up.|> tasks.task_7.State
  tasks.task_7.CreatedOrder .up.|> tasks.task_7.State
  tasks.task_7.MyOrder .up.|> tasks.task_7.State
  tasks.task_7.OrderGrant o-- tasks.task_7.State : state
  tasks.task_7.PostponedOrder .up.|> tasks.task_7.State
  tasks.task_7.RejectedOrder .up.|> tasks.task_7.State
  tasks.task_7.WithdrawnOrder .up.|> tasks.task_7.State


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
