@startuml

title __VISITOR_PATTERN_EXAMPLE's Class Diagram__\n

  namespace pattern_examples.visitor_pattern_example {
    class pattern_examples.visitor_pattern_example.BadVisitor {
        + visit()
        + visit()
        + visit()
        + visit()
    }
  }
  

  namespace pattern_examples.visitor_pattern_example {
    class pattern_examples.visitor_pattern_example.BodyElement {
        + accept()
    }
  }
  

  namespace pattern_examples.visitor_pattern_example {
    class pattern_examples.visitor_pattern_example.CarElement {
        ~ elements : Element[]
        + CarElement()
        + accept()
    }
  }
  

  namespace pattern_examples.visitor_pattern_example {
    interface pattern_examples.visitor_pattern_example.Element {
        {abstract} + accept()
    }
  }
  

  namespace pattern_examples.visitor_pattern_example {
    class pattern_examples.visitor_pattern_example.EngineElement {
        + accept()
    }
  }
  

  namespace pattern_examples.visitor_pattern_example {
    class pattern_examples.visitor_pattern_example.GoodVisitor {
        + visit()
        + visit()
        + visit()
        + visit()
    }
  }
  

  namespace pattern_examples.visitor_pattern_example {
    class pattern_examples.visitor_pattern_example.Main {
        {static} + main()
    }
  }
  

  namespace pattern_examples.visitor_pattern_example {
    interface pattern_examples.visitor_pattern_example.Visitor {
        {abstract} + visit()
        {abstract} + visit()
        {abstract} + visit()
        {abstract} + visit()
    }
  }
  

  namespace pattern_examples.visitor_pattern_example {
    class pattern_examples.visitor_pattern_example.WheelElement {
        - name : String
        + WheelElement()
        + accept()
        + getName()
    }
  }
  

  pattern_examples.visitor_pattern_example.BadVisitor .up.|> pattern_examples.visitor_pattern_example.Visitor
  pattern_examples.visitor_pattern_example.BodyElement .up.|> pattern_examples.visitor_pattern_example.Element
  pattern_examples.visitor_pattern_example.CarElement .up.|> pattern_examples.visitor_pattern_example.Element
  pattern_examples.visitor_pattern_example.EngineElement .up.|> pattern_examples.visitor_pattern_example.Element
  pattern_examples.visitor_pattern_example.GoodVisitor .up.|> pattern_examples.visitor_pattern_example.Visitor
  pattern_examples.visitor_pattern_example.WheelElement .up.|> pattern_examples.visitor_pattern_example.Element


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
