@startuml

title __VISITOR_PATTERNT_SIMPLE_EXAMPLE's Class Diagram__\n

  namespace pattern_examples.visitor_patternt_simple_example {
    class pattern_examples.visitor_patternt_simple_example.BadVisitor {
        + visit()
        + visit()
    }
  }
  

  namespace pattern_examples.visitor_patternt_simple_example {
    class pattern_examples.visitor_patternt_simple_example.BodyElement {
        + accept()
    }
  }
  

  namespace pattern_examples.visitor_patternt_simple_example {
    interface pattern_examples.visitor_patternt_simple_example.Element {
        {abstract} + accept()
    }
  }
  

  namespace pattern_examples.visitor_patternt_simple_example {
    class pattern_examples.visitor_patternt_simple_example.EngineElement {
        + accept()
    }
  }
  

  namespace pattern_examples.visitor_patternt_simple_example {
    class pattern_examples.visitor_patternt_simple_example.GoodVisitor {
        + visit()
        + visit()
    }
  }
  

  namespace pattern_examples.visitor_patternt_simple_example {
    class pattern_examples.visitor_patternt_simple_example.Main {
        {static} + main()
    }
  }
  

  namespace pattern_examples.visitor_patternt_simple_example {
    interface pattern_examples.visitor_patternt_simple_example.Visitor {
        {abstract} + visit()
        {abstract} + visit()
    }
  }
  

  pattern_examples.visitor_patternt_simple_example.BadVisitor .up.|> pattern_examples.visitor_patternt_simple_example.Visitor
  pattern_examples.visitor_patternt_simple_example.BodyElement .up.|> pattern_examples.visitor_patternt_simple_example.Element
  pattern_examples.visitor_patternt_simple_example.EngineElement .up.|> pattern_examples.visitor_patternt_simple_example.Element
  pattern_examples.visitor_patternt_simple_example.GoodVisitor .up.|> pattern_examples.visitor_patternt_simple_example.Visitor


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
